echo "tput command quick ref"
echo ""
echo "tput setab [1-7] # Set the background colour using ANSI escape"
echo "tput setaf [1-7] # Set the foreground colour using ANSI escape"
echo ""
echo "Num  Colour    #define         R G B"
echo "0    $(tput setaf 0)black$(tput sgr 0)     COLOR_BLACK     0,0,0"
echo "1    $(tput setaf 1)red$(tput sgr 0)       COLOR_RED       1,0,0"
echo "2    $(tput setaf 2)green$(tput sgr 0)     COLOR_GREEN     0,1,0"
echo "3    $(tput setaf 3)yellow$(tput sgr 0)    COLOR_YELLOW    1,1,0"
echo "4    $(tput setaf 4)blue$(tput sgr 0)      COLOR_BLUE      0,0,1"
echo "5    $(tput setaf 5)magenta$(tput sgr 0)   COLOR_MAGENTA   1,0,1"
echo "6    $(tput setaf 6)cyan$(tput sgr 0)      COLOR_CYAN      0,1,1"
echo "7    $(tput setaf 7)white$(tput sgr 0)     COLOR_WHITE     1,1,1"
echo ""
echo "$(tput bold)tput bold$(tput sgr 0)    # Select bold mode"
echo "$(tput smso)tput smso$(tput sgr 0)    # Enter standout (bold) mode"
echo "$(tput rmso)tput rmso$(tput sgr 0)    # Exit standout mode"
echo ""
echo "$(tput smul)tput smul$(tput sgr 0)    # Enable underline mode"
echo "$(tput rmul)tput rmul$(tput sgr 0)    # Disable underline mode"
echo "$(tput rev)tput rev$(tput sgr 0)     # Turn on reverse video mode"
echo "$(tput dim)tput dim$(tput sgr 0)     # Select dim (half-bright) mode"